### ISSUE TITLE
doom-themes-treemacs-theme doesn't play well with diff-hl-dired-mode

### ISSUE THREAD

**Issue by CSRaghunandan** [hlissner/emacs-doom-themes#392]
As the title suggests, this only seems to be a problem when `doom-themes-treemacs-theme` is enabled. `diff-hl-dired-mode` just stops working on dired buffers (it works when using the default theme for treemacs)

**Comment by hlissner** [comment]
Can you provides steps to provide a minimum viable dired+diff-hl setup? I don't use diff-hl, and the following doesn't work for me in any git repo, with or without treemacs or doom-themes-ext-treemacs:

```elisp
;; omitted package installation
(require 'diff-hl)
(require 'diff-hl-dired)
(dired "~/.emacs.d") ; is a git repo
(diff-hl-mode +1)
(diff-hl-dired-mode +1)
```

**Comment by CSRaghunandan** [comment]
> Can you provide steps to reproduce a minimum viable dired+diff-hl setup? I don't use diff-hl, and the following doesn't work for me in any git repo, with or without treemacs or doom-themes-ext-treemacs (in vanilla Emacs):
> 
> ```emacs-lisp
> ;; omitted package installation
> (require 'diff-hl)
> (require 'diff-hl-dired)
> (dired "~/.emacs.d") ; is a git repo
> (diff-hl-mode +1)
> (diff-hl-dired-mode +1)
> ```
> 
> There are no diffs in the margin or fringe in the dired buffer, but there are for ordinary files:
> 
> ```emacs-lisp
> (require 'diff-hl)
> (find-file "~/.emacs.d/init.el")
> (diff-hl-mode +1)
> ```

This should work:

```
(require 'diff-hl)
(require 'diff-hl-dired)
(add-hook 'dired-mode-hook 'diff-hl-dired-mode)
(diff-hl-mode +1)

(dired "~/.emacs.d") ; is a git repo
```

**Comment by hlissner** [comment]
I'm afraid I don't understand the cause of this. I'm inclined to suspect `treemacs-icons-dired-mode`, because I've stripped out all our hackery (variable-pitch remapping, load-theme advice, and our hooks) and left only the treemacs theme (which is standard usage of the treemacs theme API, afaik) and it still would not display diffs, unless I cycled `treemacs-icons-dired-mode` (i.e. `M-x treemacs-icons-dired-mode` x2). 

I am using the following:

```elisp
(require 'doom-themes)
(load-theme 'doom-one t)

(require 'diff-hl)
(require 'diff-hl-dired)
(add-hook 'dired-mode-hook 'diff-hl-dired-mode)
(add-hook 'dired-mode-hook 'diff-hl-mode) ; dired-hl-mode is a minor mode, so it should be on this hook

(require 'doom-themes-ext-treemacs)
(require 'treemacs)
(require 'treemacs-icons-dired)
(treemacs-icons-dired-mode +1)

(dired "~/.emacs.d") ; is a git repo
```


It works fine if I inject `(treemacs-load-theme "Default")` just before the `dired` call -- even if doom-themes-ext-treemacs is loaded, with all its hacks enabled.

So perhaps this is an upstream issue? Either with how Treemacs or treemacs-icons-dired handles text-icons (as opposed to its default pngs).

**Comment by CSRaghunandan** [comment]
> So perhaps this is an upstream issue? Either with how Treemacs or treemacs-icons-dired handles text-icons (as opposed to its default pngs).

I see, I'll open an issue in treemacs repo to see if the author can figure out what is going on here.

Thanks

**Comment by hlissner** [comment]
![image](https://user-images.githubusercontent.com/510883/73686031-3e72be00-4695-11ea-9cbe-15931bb2ae6c.png)

Right is default theme
Left is a minimal theme

```elisp
(require 'doom-themes)
(load-theme 'doom-one t)

(require 'diff-hl)
(require 'diff-hl-dired)
(add-hook 'dired-mode-hook 'diff-hl-dired-mode)
(add-hook 'dired-mode-hook 'diff-hl-mode) ; dired-hl-mode is a minor mode, so it should be on this hook

(require 'treemacs)
(require 'all-the-icons)
(treemacs-create-theme "new"
  :extends "Default"
  :config
  (treemacs-create-icon
   :icon (format "  %s\t" (all-the-icons-octicon "file-code" :v-adjust 0))
   :extensions ("adoc" "asciidoc" "bashrc" "c" "cabal" "cabal" "cask" "cc"
                "clj" "cljc" "cljs" "cpp" "css" "csv" "cxx" "dart"
                "dockerfile" "dockerfile" "editorconfig" "eex" "el"
                "elm" "ex" "exs" "fish" "gitconfig" "gitignore" "go" "h"
                "hh" "hpp" "hs" "htm" "html" "hy" "ideavimrc" "inputrc"
                "j2" "j2" "java" "jinja2" "jinja2" "jl" "js" "json" "jsx"
                "kt" "kt" "kts" "lhs" "lisp" "lua" "lua" "makefile" "ml"
                "mli" "nim" "nim" "nims" "nix" "perl" "pl" "plt" "pm"
                "pm6" "pp" "pp" "py" "pyc" "r" "racket" "rb" "re" "rei"
                "rkt" "rktd" "rktl" "rs" "sbt" "scala" "scm" "scrbl"
                "scribble" "scss" "sh" "sql" "sql" "styles" "sv" "tex"
                "toml" "tpp" "tridactylrc" "ts" "tsx" "v" "vagrantfile"
                "vagrantfile" "vh" "vimperatorrc" "vimrc" "vrapperrc"
                "vue" "xml" "xsl" "yaml" "yml" "zsh" "zshrc")))
(treemacs-load-theme "new")

(require 'treemacs-icons-dired)
(treemacs-icons-dired-mode +1)

(dired "~/.emacs.d") ; is a git repo
```

Either treemacs or treemacs-icons-dired appears to struggle with text icons for some reason.

**Comment by Alexander-Miller** [comment]
> Either treemacs or treemacs-icons-dired appears to struggle with text icons for some reason.

It's complicated: diff-hl calls into `dired-goto-file-1`. That works with the pngs because they are just an empty string with a display property, so I assume they are just trimmed. With doom that doesn't work because there's an actual "🗀 /foo" in there.

The onus to fix it is on me ( :disappointed: ), since any custom icon can now break dired's api. I have pushed a tentative patch that will try and turn every icon into a string-with-display-property. Hopefully that will fix things without breaking anything else. Let me know if it works @CSRaghunandan .

**Comment by CSRaghunandan** [comment]
> > Either treemacs or treemacs-icons-dired appears to struggle with text icons for some reason.
> 
> It's complicated: diff-hl calls into `dired-goto-file-1`. That works with the pngs because they are just an empty string with a display property, so I assume they are just trimmed. With doom that doesn't work because there's an actual "🗀 /foo" in there.
> 
> The onus to fix it is on me ( disappointed ), since any custom icon can now break dired's api. I have pushed a tentative patch that will try and turn every icon into a string-with-display-property. Hopefully that will fix things without breaking anything else. Let me know if it works @CSRaghunandan .

Okay, I just tried the latest patch and it looks like its not fully fixed the issue. It's only partially fixed. There are still some parts of `diff-hl-dired-mode` that are missing (like the modified files shown as blue in the fringes in the default treemacs theme).

**Comment by Alexander-Miller** [comment]
Is this restricted to a certain just a certain treemacs icon, or only to modified files or directories or is there some other pattern?

**Comment by CSRaghunandan** [comment]
> Is this restricted to just a certain treemacs icon, or only to modified files or directories or is there some other pattern?

I'm not sure, let me try to compare both and I'll get back to you.

**Comment by tshu-w** [comment]
In the latest update, doom-theme also doesn't play well with `diff-hl-mode`. The hl is block not line. Is this related?
<img width="94" alt="Screen Shot 2020-02-06 at 4 38 38 PM" src="https://user-images.githubusercontent.com/13161779/73919777-269e7280-48ff-11ea-87d7-cfcfef0b0aa9.png">

**Comment by hlissner** [comment]
@tshu-w This is unrelated to this issue. See #268

**Comment by hlissner** [comment]
@CSRaghunandan Are you still seeing this issue?
